import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientProvider from "@/components/provider";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const theme = cookies().get("theme")?.value as "light" | "dark" || "light";

  return (
    <html lang="en" className={theme}>
      <body className={inter.className}>
        <ClientProvider initialTheme={theme}>{children}</ClientProvider>
      </body>
    </html>
  );
}
